apiVersion: v1
kind: Namespace
metadata:
  name: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightbooking
  namespace: app
spec:
  selector:
    matchLabels:
      app: flightbooking
  replicas: 1
  template:
    metadata:
      labels:
        app: flightbooking
    spec:
      tolerations:
        - key: "market"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: flightbooking
          image: emirsway/flight-booking-system:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: flightbooking
  namespace: app
spec:
  type: NodePort
  selector:
    app: flightbooking
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005  # Specify the desired NodePort value

# kubectl port-forward -n app service/flightbooking 8080:8080
# http://localhost:8080
