apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      tolerations:
        - key: "market"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: grafana
          image: grafana/grafana:8.0.4
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin-password  # Replace with your desired Grafana admin password #username admin
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  # Specify the desired NodePort value

# kubectl port-forward -n monitoring service/grafana 3000:3000
# http://localhost:3000
